### ISSUE TITLE
New jobs for HIS<>Primero sync

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#1]
## Background, context, and business value

Case workers using Primero for case management need to access patient data from HIS that offers an integrated API to access patient data coming from different hospitals. Primero case workers will use a Sync button to request data from HIS will arrive to OpenFn in [this](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroSyncNotification.json) format. Upon receiving this notificaton we need to send a `GET` request to HIS to look up the patient data associated with the ID, transform and map it to Primero fields and send it to the Primero API. 

## The specific request, in as few words as possible

See the [data flow diagram](https://lucid.app/lucidchart/invitations/accept/52ee1e92-3c14-4c7c-9c46-f3e912760db1).

Create 2 jobs that execute the following steps:

1. Primero will send a notification in [this format](https://lucid.app/lucidchart/invitations/accept/52ee1e92-3c14-4c7c-9c46-f3e912760db1)  that contains a patient's: 
- `national_id` (unique ID)  OR
- `hospital_number` and `hospital_code` (jointly unique ID)
2. Send a `GET` request to the HIS API endpoint filtering by these Ids above (see API explorer [link](https://cloud1.r8way.moph.go.th:3010/explorer/) and [docs](https://drive.google.com/file/d/1Pss1Gamrqt-yeHeUMaQ5GNmyzl51i5FL/view?usp=sharing)) (we will share test IDs once we receive them). 
- See here for [an example payload](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/getPatientHIS.json) from HIS. Please note that some of the paths are incomplete and will be updated once we have access to test data.
3. Transform and map the fetched patient data according to the [mapping specifications](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit?usp=sharing). In case the [Primero Output Value (EN)](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=M:M) is `(OPEN TEXT)` (e.g. [here](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=M5) ) we map the fetched HIS value directly (after potential transformation). If it contains categories (e.g. [here](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=M11) we have to map the values onto those categories.

## state.json

1. Notification from Primero: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroSyncNotification.json
2. Sample payload from HIS (note that we don't _yet_ have a payload with all source values included in it... we've requested better sample data, so please build to spec in the meantime): https://github.com/OpenFn/primero-thailand/blob/master/sampleData/getPatientHIS.json

For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

## adaptor

1. `language-http` to connect to HIS API
2. `language-primero` to connect to Primero v2 API (see docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs )

## trigger

`{ "data": {"record_type": "case"}}`

## expression.js
Create 2 jobs...
1. To `get(...)` from HIS API
2. To `upsertCases(...)` in Primero

## output.json

For example if we receive `marrystatus: "4"` from HIS we upsert value`maritial_status: "divorced_separated"` to Primero.

### side effects

1. upsert case data to Primero using `id` (e.g., `3e5a1131-084f-4186-8c06-44ecceab84a5`) as the externalId

### output.json

See sample JSON of a Primero case record: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroCaseOutput.json

**Comment by aleksa-krolls** [comment]
@lakhassane A fresh new issue for you from UNICEF Thailand is ready. Ping @ritazagoni when you're ready to walk through it to confirm the spec is confirm and ready to start work. 

cc @stuartc you may be interested in listening to this hand-off
@taylordowns2000 please add this repo to your zenhub during standup

**Comment by aleksa-krolls** [comment]
@lakhassane Asking Thailand team about the certificate issue, but here is the response I am able to successfully get via Postman: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/getUsersLogin_HIS.json

Can we continue to draft this job based on this response? Otherwise, I suggest holding on job #1 and proceeding with #2 using the sample payload state and mapping specs provided.

**Comment by aleksa-krolls** [comment]
@lakhassane Can you please configure whatever you have drafted with the relevant `configuration` in Credentials 
on Production here: 
https://openfn.org/projects/p5kaap/jobs

**Comment by ritazagoni** [comment]
@lakhassane feedback from HIS team on HIS API SSL certificate issue: 
please put a parameter ‘—insecure’ or ‘-k’
Example of curl --insecure 'https://cloud1.r8way.moph.go.th:3010/api/Users/login’

_If you are able to get a successful response from the HIS_, can you please create a new file in `sampleData` to log the JSON response to use as a new state.

**Comment by ritazagoni** [comment]
@lakhassane I added a new test ID to work with to example state: https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroNotification.json

**Comment by aleksa-krolls** [comment]
@lakhassane Job is throwing `401 unauthorized` error but we are able to authorize on Postman: https://www.openfn.org/projects/p5kaap/runs/r5eagppx

Please see this slack thread and consider changing the `configuration` on prod: https://openfn.slack.com/archives/G2LJCFFDW/p1611129664025900?thread_ts=1610440707.006900&cid=G2LJCFFDW

**Please test the job flow with this message:** https://www.openfn.org/projects/p5kaap/messages/mz7gb4vm

**Comment by aleksa-krolls** [comment]
@lakhassane thanks auth is now working. This allows us to fetch a new version of state to test job 2. 

But see `TypeError [Error]: Cannot read property 'substring' of undefined` thrown in job 2. https://www.openfn.org/projects/p5kaap/runs/rn59kw7d

**Comment by lakhassane** [comment]
@aleksa-krolls @ritazagoni we corrected the authorization error on this one. However there might still be a memor problem on their server to check with them: `Sort exceeded memory limit of 104857600 bytes`
https://www.openfn.org/projects/p5kaap/runs/rx8wbkg4

**Comment by aleksa-krolls** [comment]
@lakhassane Updates from Thailand! We have a slightly new API endpoint for the HIS source system. 
1. New `GET https://cloud1.r8way.moph.go.th:3010/api/people?filter={"where":{"cid":"state.data.national_id"},"include":"interventions", "limit":1}&access_token=SEE-LP`
2. Explorer: https://cloud1.r8way.moph.go.th:3010/explorer/#/person (we now need to access `/person` rather than `/vPerson`)

I've run the following on Postman using `national_id: 3470200088611` and got [this response](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_personEndpoint.json). 

```curl
GET https://cloud1.r8way.moph.go.th:3010/api/people?filter={"where":{"cid":"3470200088611"},"include":"interventions", "limit":1}&access_token=SEE-LP
```


## Request 
1. Can you please implement the appropriate changes to job `1-getPatientData.js`? 
2. Then test against this message: https://www.openfn.org/projects/p5kaap/messages/mqppj7vj

See LP for `New Thailand MOPH HIS API` cc @ritazagoni

**Comment by lakhassane** [comment]
@aleksa-krolls runs succeeding: 
1. https://www.openfn.org/projects/p5kaap/runs/r44xgx6e
2. https://www.openfn.org/projects/p5kaap/runs/rpdapa6g

There might be a slight update on job 1 once we finalize those changes on `language-http`

**Comment by aleksa-krolls** [comment]
@lakhassane Two things... 

(1) I see `case_id` is hardcoded in job #2 and don't recall why..
https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L188

Please update job #2 so that `case_id` is dynamically mapped from the state the triggers the job #1 flow - use this state and make sure when this runs on prod, job#2 performs a case _update_ operation on case `a094ae8b-3fdf-4f86-8462-5c8877adb9c3`: 
https://www.openfn.org/projects/p5kaap/messages/mk559jgr

This state triggers job #1...
```json
{
  "__query_params": {},
  "case_id": "a094ae8b-3fdf-4f86-8462-5c8877adb9c3",
  "national_id": "1470200049121",
  "record_type": "case"
}
```
Pass `case_id` to job #2 state --> and then use to upsert cases in Primero. 

(2) @ritazagoni found that it doesn't look like this job is syncing any of the mappings when updating cases. 
See run log here where on L33 it looks like no data (name, age) are being posted to Primero: 
https://www.openfn.org/projects/p5kaap/runs/rwam6kyz

Is this data object not being correctly passed to the upsert function? 
https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L212

**Comment by lakhassane** [comment]
@aleksa-krolls I made the changes and run on prod.

**Comment by aleksa-krolls** [comment]
@lakhassane Are you sure my #2 is resolved? This run looks exactly the same as before (no `name_first`, `age`, etc.  fields mapped to the Primero record - at least no logged on L33 - and this data is still missing in the Primero system): https://www.openfn.org/projects/p5kaap/runs/rk5746gy

Here is the Primero case I'm looking at where this basic info is missing (https://demo-care-thai-kids.primero.org/v2/cases/d7869de5-d05b-4337-a865-5976de8d8b4d - see LP for `Primero Staging Thailand`). 

Here again are the API docs for updating a case in Primero: https://github.com/primeroIMS/primero/blob/development_v2/app/controllers/api/v2/docs/cases/id/patch.md
