### ISSUE TITLE
Return unique lab results for every 1 intervention

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#10]
## Background
This issue came up when investigating issue #9. See #1 for solution background. 

## Request
As discussed if there are more than 1` provis_labcode` for the same intervention, then take the most recent one determined by `report_date` to ensure we’re only mapping unique lab results for every 1 intervention. 

## expression
1b-upsertCases.js

## output 
Primero forms each have 1 field for every lab result type (e.g., `pregnancy_test_21c37e2`). So if you see 2 `pregnancy_test_21c37e2` lab results... only return the latest one.

**Comment by lakhassane** [comment]
@aleksa-krolls About this one, Im not sure anymore if it's a bug or a sample data mistake. 
We were supposed to take the most recent intervention if there were more than 1 `provis_labcode` for the same intervention.

However, those interventions with the same provis_labcode have the same `report_date`, `report_time` and even same `receive_date` and `receive_time`.
So no matter what we do it will always get overwritten by the last object.

I can provide you with an intervention that have this issue.

**Comment by aleksa-krolls** [comment]
@lakhassane please share the intervention that you saw... but I think this is a sample data issue, haven't seen elsewhere.

**Comment by lakhassane** [comment]
@aleksa-krolls just sent privately

**Comment by ritazagoni** [comment]
HIS data quality issue.
