### ISSUE TITLE
Change diagnosis output to include `icd10` + ' ' +`diag_name`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#11]
## Background
This issue came up when investigating issue #9. See #1 for solution background.

## Request
Currently diagnosis outputs the `diag_name` (e.g., `'Tuberculous peripheral lymphadenopathy'`). 
We want to add `icd10` + ' ' +`diag_name` ==> `'A182 Tuberculous peripheral lymphadenopathy'`

## state
```
"diagnosis": [
                    {
                        "diagtype": "1",
                        "diagtype_name": "1.Primary Disease",
                        "icd10": "A182",
                        "diag_name": "Tuberculous peripheral lymphadenopathy",
                        "spclty": "01",
                        "spclty_name": "แผนกอายุรกรรม",
                        "doctor": "ว27896",
                        "doctor_name": "แพทย์คณา เกษมทรัพย์",
                        "staff": "แพทย์คณา เกษมทรัพย์",
                        "date": "2021-03-24",
                        "time": "07:16",
                        "pt_status": "O"
                    },
```

## expression
1b-upsertCases.js

## output
Diagnosis should output as `${icd10} ${diag_name}` (e.g., `'A182 Tuberculous peripheral lymphadenopathy'` for the above state)

**Comment by lakhassane** [comment]
@aleksa-krolls you are good to go
