### ISSUE TITLE
Revise subform unique ID to match regex format

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#16]
## Background, context, and business value

Currently when setting `physical_check_2` subform unique IDs in job `1b-upsertCases.js`, we use `intervention_id` and `patient_cid` coming from HIS: https://github.com/OpenFn/primero-thailand/blob/c53fe18887f8aa136e4f905c4b620f95881e42cf/jobs/1b-upsertCases.js#L478. As a Primero constraint, this ID has to match the following regex: `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, for example: `"unique_id":"f44bf3f4-0af4-4cfe-a125-dde57db400b3"`

## The specific request, in as few words as possible

As we need to be able to generate the same unique ID each time we handle an intervention, I suggest implementing the following steps in the [`1b-upsertCases.js`](https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js) job
1. Take `intervention.id`
2. Pad it with a constant set of characters to achieve needed length
3. Format with `-` -s to achieve needed final format.

## state.json

For HIS login see LP `Thailand MOPH HIS webservice (UNICEF)`
For Primero login see LP `Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpoint14April.json)

## output.json

The `physical_check_2` subform unique ID should match the regex `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, for example `"unique_id":"f44bf3f4-0af4-4cfe-a125-dde57db400b3"`.

**Comment by lakhassane** [comment]
@ritazagoni I build the unique Id using the regex and the intervention id as we discussed. Instead of completing the length with 0s I just used a substring of the `CID`.

Here is an example generated: `"unique_id": "6059173c-962a-71ec-9cb5-0d9614109000",`
