### ISSUE TITLE
Scrub HTTP request header details from logs on run failure

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#17]
## Describe the bug
See email with Pavel and L594 of this run: https://www.openfn.org/projects/p5kaap/runs/r6g78k7w

## To Reproduce
This is a flow job triggered by a notification from Primero: https://www.openfn.org/projects/p5kaap/runs/rwa89j8b

**Comment by aleksa-krolls** [comment]
PR submitted to adaptor: https://github.com/OpenFn/language-primero/pull/29/files#diff-97cefc266d49ebb7b1c526cf9ee28a24deb0664c92b266eb98ff81e6f31dad1eR27-R31

@taylordowns2000 to follow up with @lakhassane

**Comment by aleksa-krolls** [comment]
@taylordowns2000 confirming you won't push to prod until chatting with Mamadou? 
@ritazagoni to update the Primero team on expected timeline accordingly today.

**Comment by taylordowns2000** [comment]
I'd actually like to discuss this with Stu today and release a new version
on NPM. Give me ~45 minutes and I'll have an update.

**Comment by taylordowns2000** [comment]
This is out on  version [`v2.2.7`](https://www.npmjs.com/package/@openfn/language-primero/v/2.2.7) and can be used in production whenever.

I'll add it to the next platform release, but if it's needed before then please manually select the adaptor by typing `primero` and `v2.2.7` into the npm-adaptor-select dialog.
