### ISSUE TITLE
Revise ` new pregnancy` subform unique ID to match regex format

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#18]
## Background, context, and business value

Currently when setting `new_pregnancy` `unique_id` we use `date_of_report+current_gestational_week` as `unique_id`, see https://github.com/OpenFn/primero-thailand/blob/f379464298cf94608f9638fb44d926f90b28c8dd/jobs/1b-upsertCases.js#L509

As a Primero constraint, this ID has to match the following regex: `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, for example: "unique_id":"f44bf3f4-0af4-4cfe-a125-dde57db400b3"
## The specific request, in as few words as possible

As we need to be able to generate the same unique ID each time we handle a `new_pregnancy`, I suggest implementing the following steps in the 1b-upsertCases.js job

1. Take `date_of_report+current_gestational_week`
2. Pad it with a set of characters to achieve needed length (e.g. using patient `cid` as in #16 )
3. Format with `-` -s to achieve needed final format.

## state.json

For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointAnc.json)

## output.json
The `new_pregnancy` subform unique ID should match the regex `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, for example `"unique_id":"f44bf3f4-0af4-4cfe-a125-dde57db400b3"`.

**Comment by lakhassane** [comment]
@ritazagoni you are good to go here

**Comment by ritazagoni** [comment]
success! https://www.openfn.org/projects/p5kaap/runs/rrk8wgz5
