### ISSUE TITLE
Update mappings in job `1b-upsertCases.js`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#2]
## Background, context, and business value

We have more complete mappings for upserting cases in Primero with data retrieved from HIS. The mappings are not entirely complete but we are only expecting additional fields and no structural changes. See original issue #1 

## The specific request, in as few words as possible

**New mappings**
Update `1b-upsertCases.js` based on the Primero-HIS [mapping sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968)

[Column C](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=C:C) contains the full JSON path for the input HIS data. 

[Column K](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=K:K) contains the full JSON path for the API fields to be upserted in Primero.

Where any of the values above are missing the mapping information is still incomplete, please ignore for the time being.

Fyi, the following mappings have already been added to the job update the Primero record's sync status when we update a record:

```
PATCH /api/v2/cases/:id: 

{   "data": { 
     "mark_synced": true,      
     "mark_synced_url": "https://www.openfn.org/inbox/<inbox-id>",      
...    
             }
 }
```

## state.json
LP `Primero Thailand Demo API User (Open Function)`

[Example payload from HIS](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_completeHISPersonEndpoint.json)

## adaptor

`language-http` to connect to HIS API
`language-primero` to connect to Primero v2 API (see docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs )

## trigger

[`When job 1.a. Get Patient from HIS succeeds.`](https://www.openfn.org/projects/p5kaap/triggers/t9zjdb)

## expression.js

Update job `1b-upsertCases.js`.

## output.json
[Example output for Primero](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroCaseOutput1March.json)

For example if we receive marrystatus: "4" from HIS we upsert value `maritial_status: "divorced"` to Primero.

### side effects

Upsert case data to Primero using id (e.g. `3e5a1131-084f-4186-8c06-44ecceab84a5`) as the externalId.

**Comment by ritazagoni** [comment]
@lakhassane I updated mappings in the [sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968). Updated version is named `v2` in version history which you can compare with `v1` from yesterday. Please let me know if this makes the process easier and if you have any feedback on how to improve it.

**Comment by lakhassane** [comment]
Thanks @ritazagoni it has been useful to see evolution in the mappings :)

**Comment by aleksa-krolls** [comment]
@ritazagoni if there's any further changes required, please submit a new issue so that engineering can put a new estimate on any changes. Feel free to reference this original issue in any subsequent ones.
