### ISSUE TITLE
Diagnosis output of `icd10 + ' ' +diag_name` is empty

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#20]
## Describe the bug

See original issue in #11. In the most recent intervention we are supposed to [map](https://github.com/OpenFn/primero-thailand/blob/8cb8d1a68d6dd46bf5c278e9071b7fa22f7c9837/jobs/1b-upsertCases.js#L563-L600) diagnosis fields based on `icd10` and `diagtype`, and output `icd10 + ' ' +diag_name`. 

However currently we're outputting an empty string even though we have `icd10`, `diagtype` and `diag_name` available. 
See data fetched from HIS ([from line 128](https://www.openfn.org/projects/p5kaap/runs/r7xjam4r)) and the upsert (from [line 1777](https://www.openfn.org/projects/p5kaap/runs/rzd5j9am)).

For example, we expected the output `main_diagnosis__04438ee": "R51 Headache"`.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/p5kaap/runs/rzd5j9am

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L563-L600

## state.json

For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpoint14April.json)

See new job set up on the [platform](https://www.openfn.org/projects/p5kaap/jobs/jyd9xa)

## adaptor
1. `language-http` to connect to HIS API
2. `language-primero` to connect to Primero v2 API

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. Please test the change on OpenFn.org by re-running [this run](https://www.openfn.org/projects/p5kaap/runs/r7xjam4r) (parent job for upsert) and confirming success.

**Comment by lakhassane** [comment]
@ritazagoni there were a typo in how we defined those diagnosis field. 
However, we use `recentInterventions` to build them. In recentIntervention, we have only one `diagnosis` object

```
diagnosis [
  {
    icd10: 'M4806',
    diag_name: 'บรเวณเอว',
    diag_thai_name: '',
    diagtype: '1',
    diagtype_name: 'Principal Diagnosis',
    doctor: 'ว62364',
    doctor_name: 'นายภูวิศ วิเศษสา',
    staff: '62364',
    spclty: '02',
    spclty_name: '02:ศัลยกรรม',
    date: '2021-06-28',
    time: '7:50:19'
  }
]
```
So the output will look like this `"main_diagnosis__04438ee": "M4806 บรเวณเอว",`

**Comment by ritazagoni** [comment]
Gotcha, thanks. Didn't manage to find the most recent one :)
