### ISSUE TITLE
Revise new pregnancy subform unique ID 

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#22]
## Background, context, and business value

See original request at #18 

We are currently using `date_of_report+current_gestational_week` to create a `unique_id` for the `new_pregnancy` subform, adding characters from the `cid` to match required format. 
However, `date_of_report` is sometimes empty.
See latest failed run for error: https://www.openfn.org/projects/p5kaap/runs/r9wnxj89

## The specific request, in as few words as possible

To overcome this, use following `new_pregnancy` `unique_id` creation logic:

1. Take number of item in `anc` list (1 for first item, 2 for second etc.)
2. Take `date_of_report` (e.g. `20150811`)
3. Pad it with a set of characters to achieve needed length (e.g. using patient `cid` as in #16 )
4. Pad it with a constant set of characters if necessary to achieve needed length
5. Format with `-` -s to achieve needed final format.

For two items in the anc list, the two unique IDs would look like this:
1. `120150811-1101-1101-1101-111111111111`
2. `220150811-1101-1101-1101-111111111111`

## state.json

For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointAnc.json)

## output.json
The `new_pregnancy` subform unique ID should match the regex `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, for example `"unique_id":"f44bf3f4-0af4-4cfe-a125-dde57db400b3"`.

Jira ref [OFGS-44]

[OFGS-44]: https://openfn.atlassian.net/browse/OFGS-44

**Comment by lakhassane** [comment]
@ritazagoni I assume in point 1 you meant `position of item in an` instead of number (which might be different). Also I think it's `ga_week` that is empty but not `date` if you look at the output `20150810-unde-fine-d141-110135085100` (date is `20150810`)

**Comment by ritazagoni** [comment]
Yes exactly for both @lakhassane

**Comment by lakhassane** [comment]
yes :) I made the changes.

**Comment by aleksa-krolls** [comment]
Looking good! https://www.openfn.org/projects/p5kaap/runs/rya49k6e
