### ISSUE TITLE
Mapping to `undefined` key before uploading to Primero

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#27]
## Describe the bug
See run: https://openfn.org/projects/pderjw/runs/0616534c-1eae-74ba-928d-8b77717d7da7

L326 `"undefined": "2330010 Limited oral evaluation - problem focused, 23871C1 Resin-based composite - one surfaces, posterior-permanent"`

Why are we mapping to a key called `undefined`? Throwing an error in Primero. 

 **UPDATE**
If `diagtype` = `6`, `7`, or other value not currently specified in the [mapping sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968), map it the same way as `diagtype=4`, ie. `other_diagnosis_a692bec`

## To Reproduce
Feel free to re-run the parent run on prod to test: https://openfn.org/projects/pderjw/runs/0616534b-a987-72b3-8970-0bde4874ca11

### expression.js
jobs/1b-upsertCases.js

### state.json
SEE `Primero Thailand API User`
See parent run: https://openfn.org/projects/pderjw/runs/0616534b-a987-72b3-8970-0bde4874ca11

**Comment by lakhassane** [comment]
@aleksa-krolls we are having this issue because when we are mapping diag_type we had this mapping object below
```js
const diagType = {
      1: 'main_diagnosis__04438ee',
      2: 'co_morbidity_d3dfab2',
      3: 'complications_123ecae',
      4: 'other_diagnosis_a692bec',
      5: 'external_cause_of_injury_8451818',
    };
```
However, in the message we have a diag_type : 6 that wasn't planned. So it mapped `undefined`. I made a correction to ignore when the value of diag_type is not in the object above. But you might need eyes on this because it feels like we are losing data then.

Find the latest run: https://openfn.org/projects/pderjw/runs/0616577b-6285-7355-a076-344c1c296bae

**Comment by ritazagoni** [comment]
**UPDATE** @lakhassane please see request from UNICEF:
If `diagtype` = `6`, `7`, or other value not currently specified in the [mapping sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968), map it the same way as `diagtype=4`, ie. `other_diagnosis_a692bec`

**Comment by lakhassane** [comment]
@ritazagoni I mapped accordingly. Anything non specified diagtype with map to `other_diagnosis_a692bec`

**Comment by ritazagoni** [comment]
thanks @lakhassane!
mapping sheet updated with changes.
