### ISSUE TITLE
HIS requests: Only query last 50 visits in GET request

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#28]
## Background, context, and business value
We're trying to optimize the runtime for requests made to the HIS after seeing load testing results. 

## The specific request, in as few words as possible
When we send a GET request to query patient information, the client has requested to only query 50 visits at a time. 
The client suggested adding these parameters to our GET request: 
```
Get Data
url: https://cloud1-r8way.moph.go.th:3010/api/people/findOne
method: GET
parameter:
access_token: token
raw JSON:
{
"filter": {
"where": {
"cid": "xxxxxxxxxxxxx"
},
"include": {
"relation": "interventions",
"scope": {
"order": "vstdate DESC",
"limit": 50
}
}
}
}.
```

## adaptor 
HTTP 

## expression
https://github.com/OpenFn/primero-thailand/blob/393eea61aa96e6373452be76c6f987d802864300/jobs/1-getPatientData.js

## state
See LP for `MOPH Thailand HIS API - PROD`
This patient has 300+ visits in HIS, but our query should only return 50: https://www.openfn.org/projects/pderjw/messages/0615edfe-3363-78bf-bfa5-4ee2dc267dcf

Feel free to test on prod once you've fixed... we should no longer see a timeout.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @elias-ba fyi, one suggestion has come back from the Thailand MOPH. Can you please check out sometime today?

**Comment by lakhassane** [comment]
@aleksa-krolls this is fixed: https://www.openfn.org/projects/pderjw/runs/061684cd-9940-72ee-9a18-558b809114c8

But Im curious, we need to fetch only 50 visits. Does it mean the rest is ignored?
