### ISSUE TITLE
Update job `1b-upsertCases.js` with new mappings

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#3]
## Background, context, and business value

We have more complete mappings for upserting cases in Primero with data retrieved from HIS. The mappings are not entirely complete but we are only expecting additional fields and no structural changes. See original issue #1 and previous round of updates in issue #2 .

## The specific request, in as few words as possible

**New mappings on white rows** in
Update `1b-upsertCases.js` based on the Primero-HIS [mapping sheet v4]. (https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968) 

[Column C](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=C:C) contains the full JSON path for the input HIS data. 

[Column K](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=K:K) contains the full JSON path for the API fields to be upserted in Primero.

Where any of the values above are missing the mapping information is still incomplete, please ignore for the time being.

## state.json
LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

[Updated example payload from HIS](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISPersonEndpoint12March.json)

## adaptor

`language-http` to connect to HIS API
`language-primero` to connect to Primero v2 API (see docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs )

## trigger

[`When job 1.a. Get Patient from HIS succeeds.`](https://www.openfn.org/projects/p5kaap/triggers/t9zjdb)

## expression.js

Update job `1b-upsertCases.js`.

## output.json
[Example output for Primero](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/primeroCaseOutput1March.json)

For example if we receive marrystatus: "4" from HIS we upsert value `maritial_status: "divorced"` to Primero.

### side effects

Upsert case data to Primero using id (e.g. `3e5a1131-084f-4186-8c06-44ecceab84a5`) as the externalId.

**Comment by aleksa-krolls** [comment]
@lakhassane please take this on before vcs. Let @ritazagoni know if you have any questions.

**Comment by ritazagoni** [comment]
@lakhassane The mappings have [changed](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968) on lines `153, 154, 155, 156, 158`. Instead of `diagtype = 1` or `diagtype = 2` etc. we now have to expect both `diagtype = 1` or `diagtype = 01` etc. Please update job to accomodate both formats.

**Comment by ritazagoni** [comment]
hey @lakhassane we'd need a few more changes based on test results and additional fields. See white rows in [mapping sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968):
1. `line 21` HIS field name turns out to be `aducate` instead of `educate`
2. `line 145` new mapping
3. `lines 153, 154, 155, 156, 158` we only need to map values from most recent intervention based on `{"interventions":[{"vstdate"}]}`

Ping me for any questions or testing.

**Comment by ritazagoni** [comment]
@lakhassane Additional specs for `line 32` and `145`.
We need to generate a `uuid` called `unique_id` 
- `line 32`: for each item in the `physical_check_2` list ([specs here](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=P32)
- `line 145`: for the item in the `new_pregnancy" list ([specs here](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=P145))

**Comment by ritazagoni** [comment]
thanks for the updates @lakhassane! Added [specification](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=145:146) for the last mapping and a [sample state](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointWithAnc.json) containing the `anc` section. Note we're still missing the field `ga` but team has confirmed that will be part of the payload.

**Comment by ritazagoni** [comment]
hey @lakhassane, updates in the specs:
1. `lmp` and `pe` fields added, see [mapping sheet](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=36:37). New [sample state](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpoint14April.json) including the fields.
2. For creating `uuid` for `physical_check_2` items, please follow the specifications [here](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968&range=P32).

**Comment by lakhassane** [comment]
@ritazagoni I added the new mappings

**Comment by aleksa-krolls** [comment]
@lakhassane job fails with the error `TypeError [Error]: Cannot read property 'reduce' of undefined`. 

When fixed, **please test on prod with BOTH to confirm it's working.** Use this state to get data from HIS....
https://www.openfn.org/projects/p5kaap/messages/mv76qgng
https://www.openfn.org/projects/p5kaap/messages/m583mdkn

**Comment by lakhassane** [comment]
Made both of them working @aleksa-krolls 
https://www.openfn.org/projects/p5kaap/runs/rbgkw3d7

**Comment by aleksa-krolls** [comment]
@ritazagoni please test this morning to flag if any other changes should be put in the top of the backlog.

**Comment by ritazagoni** [comment]
@lakhassane A request for cleaning incoming data in job: `1-getPatientData.js `
We might get `national_id` in the following format from Primero, see example message: https://www.openfn.org/projects/p5kaap/messages/m66dgjjd
```
"national_id_no": "14-1100-00763-63",
```
Please add step to job `1-getPatientData.js` to remove `-`-s from `national_id` so that we use the correct `national_id`: `1411000076363`

**Comment by lakhassane** [comment]
@ritazagoni about your last comment do you mean to clean it in job 2 (upsertCases) because that's where we do to the mapping and not in job 1?

Second thing do you also mean `We might get national_id in the following format from the HIS` (instead of from Primero) it's a small thing but it matters in where I should address this.

**Comment by ritazagoni** [comment]
@lakhassane let me create a new issue for this!

**Comment by ritazagoni** [comment]
@lakhassane one change request:
Currently when we're mapping rows [`154-157` and `159`](https://docs.google.com/spreadsheets/d/1f1fT3qmM4mKT98AaJ0ArlgONQRC-W9ghoa-j4BswwbM/edit#gid=266795968), we're adding the value of the `icd10` key to the payload. Instead, we would need to use the value of `diag_name`. No other change is needed, the mapping logic stays the same.

**Comment by aleksa-krolls** [comment]
@lakhassane on this one... is it as simple as finding and replacing `icd10` with `diag_name`? If yes @ritazagoni can implement.

**Comment by lakhassane** [comment]
@aleksa-krolls that's proly that. But Im not sure how it would be, `diag_name`have multiple value in it
