### ISSUE TITLE
Handle HIS error code received  "1.a. Get Patient from HIS" run

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/primero-thailand#4]
## Background, context, and business value

See original issue #1 .

When querying data from HIS with job `1.a. Get Patient from HIS`  we may receive a `404` or other error code. See an example error response [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointNotFound.json). 

In these cases we want to send a different payload to Primero as currently in job `1.b Upsert Cases`. 

## The specific request, in as few words as possible

Currently when the `1.a. Get Patient from HIS` it triggers the `1.b Upsert Cases` which sends the payload `mark_synced: true` and retrieved patient data to Primero.
If job `1.a. Get Patient from HIS"` receive an error response from HIS, we want to send `mark_synced: X` *exact value to be confirmed* to Primero and no patient data or undefined values. This can be done in a new job that is triggered by a failed run of `1.a. Get Patient from HIS` or with branching logic in `1.b Upsert Cases`. See flow logic [here](https://lucid.app/lucidchart/invitations/accept/inv_9d0e4836-d766-437f-b49f-1a4368d23b77?viewport_loc=-11%2C-11%2C2123%2C1081%2C0_0).

**UPDATE**
If job `1.a. Get Patient from HIS` receives an error response from HIS, we want to distinguish between two types of error:
**Type 1.** If `cid` not found, we receive `statusCode: 404`, `message: "Unknown \"person\" id \"undefined\"."`,  `"code": "MODEL_NOT_FOUND"`
See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointNotFound.json)

In this case, we want to send the following in `1.b Upsert Cases`.

```
data : {
    mark_synced_status: "not_found",
    mark_synced_url: ${inbox},
    record_id: ${primero_record_id}
}
```
**Type 2.** Any other error and error code that causes job `1.a. Get Patient from HIS"` to fail.

In this case, we want to send the following in `1.b Upsert Cases`.

```
data : {
    mark_synced_status: "failed",
    mark_synced_url: ${inbox},
    record_id: ${primero_record_id}
}
```

## state.json

LP Primero Thailand Demo API User (Open Function) (Note... this user is for basic auth.)

See example HIS error status response [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpointNotFound.json).

## adaptor

language-http to connect to HIS API
language-primero to connect to Primero v2 API (see docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs )

## trigger
Should only run on fail... `catch fail` trigger?

## expression.js

Either update job `1.b Upsert Cases`  OR create new job.

## output.json

Example output for Primero:
Type 1 error:
```
data : {
    mark_synced_status: "not_found",
    mark_synced_url: ${inbox},
    record_id: ${primero_record_id}
}
```

Type 2 error:
```
data : {
    mark_synced_status: "failed",
    mark_synced_url: ${inbox},
    record_id: ${primero_record_id}
}
```

### side effects

Send specified `mark_synced_status` and `mark_synced_url` data to Primero.

**Comment by lakhassane** [comment]
@ritazagoni having another job `1c-upsertFailedCases.js`is fine. So I can draft it and you ping me whenever you have the `mark_synced`value.

Just confirming that this is the only payload we need to send to Primero in that case:
```
data : {
    mark_synced: X;
    mark_synced_url: ${inbox}
}
```

**Comment by ritazagoni** [comment]
Sounds good, thanks @lakhassane .
We also need the `record_id` be used as `external_id` by the `upsert`:
```
data : {
    mark_synced: X;
    mark_synced_url: ${inbox}
    record_id: ${primero_record_id}
}
```

**Comment by lakhassane** [comment]
So I pushed a draft and will wait for update on the missing field.

**Comment by aleksa-krolls** [comment]
@lakhassane we're not going to hear back from Primero team about the missing field. So can you please finish the job and configure in Production here so that we can test? 
https://www.openfn.org/projects/p5kaap/jobs

@ritazagoni given that the sync statuses won't be available for a another few days, for UAT I think we should test to ensure that the sync button is at the very least reenabled when an error is caught.

**Comment by ritazagoni** [comment]
@lakhassane Until we get final info from Primero on the missing field, please configure the `1c-upsertFailedCases.js` to send the following data to Primero:

```
data : {
    mark_synced: true,
    mark_synced_url: ${inbox},
    record_id: ${primero_record_id}
}
```

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni Has this error been fixed? Was clicking around and saw a recent failure of this flow with the error: `TypeError: Cannot read property 'body' of undefined`

https://www.openfn.org/projects/p5kaap/runs/rg5nag76

**Comment by lakhassane** [comment]
@aleksa-krolls this was a typo in the `adaptor` but the case was still successfully created. Im pushing a new version

**Comment by aleksa-krolls** [comment]
@lakhassane Is the new adaptor version ready? Please re-run this on prod to make sure it's working today: 
https://www.openfn.org/projects/p5kaap/runs/rg5n5ax8

**Comment by ritazagoni** [comment]
@lakhassane we shouldn't be trying to create case, we should be updating the existing one https://www.openfn.org/projects/p5kaap/runs/raaeazre

**Comment by lakhassane** [comment]
@ritazagoni I see you re-opened the issue but with no comments. Any feedback?

**Comment by ritazagoni** [comment]
Ah sorry edited the description, added an UPDATE section to the request! @lakhassane

**Comment by aleksa-krolls** [comment]
@lakhassane What's the status here? Are all changes pushed to Github? We need to send an update to Thailand team this morning and want to make a small adjustment to the mappings ourselves, so let us know how it's going, thanks :)

**Comment by lakhassane** [comment]
Hey @aleksa-krolls yes it is all pushed to Github. You are free now to test for this one.

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni and I just saw an error where this `jobs/1c-upsertFailedCases.js` failed (see run: https://www.openfn.org/projects/p5kaap/runs/r44mnkwz) when the job 1 to get information from HIS timed out on OpenFn (see run: https://www.openfn.org/projects/p5kaap/runs/rg5nja88). 

Can you please adjust the job `jobs/1c-upsertFailedCases.js` to also run in scenarios where the OpenFn job 1 run times out or fails?

**Comment by lakhassane** [comment]
@ritazagoni corrections done in here for timeout runs.
https://www.openfn.org/projects/p5kaap/runs/rrkz9j6n
