### ISSUE TITLE
Duplicate `Unexpected Pregnancy` form created every sync with HIS

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#6]
## Describe the bug
Every time we "sync" [this Primero case](https://demo-care-thai-kids.primero.org/v2/cases/3d9a5570-fe40-4138-be5b-1f7d1d37ecc5) with `record_id: 3d9a5570-fe40-4138-be5b-1f7d1d37ecc5` and `national_id: 1411100151154`... then duplicate `new_pregnancy` forms are created... 
![image](https://user-images.githubusercontent.com/16758106/116635214-d75eba80-a966-11eb-8641-451795ad9334.png)

## To Reproduce
Here's the latest run that created another dupe `new_pregnancy` with the date `2021-04-02`: 
https://www.openfn.org/projects/p5kaap/runs/r89eby46

### expression.js
https://github.com/OpenFn/primero-thailand/blob/3f509483e34a4068741bfb3a3acbbc47545bab17/jobs/1b-upsertCases.js#L318-L329

### state.json
See LP for `Primero Thailand Demo API User (Open Function)`. 
Re-run the sync with HIS flow - see this run: https://www.openfn.org/projects/p5kaap/runs/rrkz7g4w

## Expected behavior
If no unique `id` is available in the HIS state data for `new_pregnancy` forms... then let's create a custom `unique_id` that we can check before creating new forms. This custom `unique_id` can be set as `${date_of_report}${current_gestational_week}`.

**Comment by lakhassane** [comment]
@aleksa-krolls for a bit of clarification here, do you mean we need to create a `unique_id` field that is added to the pregnancy object?
```js
 const ancObj = { 
       unique_id: "",
       current_gestational_week: ancElement.ga_week, 
       date_of_report: ancElement.date, 
       source_of_information_647b9db: 'his' //Source of Information 
     }; 
```

**Comment by aleksa-krolls** [comment]
@lakhassane yes, so I think with all the other forms we make use of `unique_id` to ensure we don't insert duplicate forms... I didn't see that with these pregnancy forms... therefore we insert dupes every time we sync. 

So yes, please create a new `unique_id: ${date_of_report}${current_gestational_week}`... and ensure we upsert these pregnancy forms with every sync.
