### ISSUE TITLE
`Physical_check_2` forms include 'undefined' values

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#7]
## Describe the bug
Search for `undefined` in this run log: https://www.openfn.org/projects/p5kaap/runs/r9wxbbk5
What's particularly strange is the `"undefined"` destination field defined. 
```
 "undefined": "13.4 % (11 - 16 %)",
```

## To Reproduce
Re-run the sync with HIS using `cid: 1411100090660`. See run:  https://www.openfn.org/projects/p5kaap/runs/ryaewwk7

### expression.js
1b-upsertCases.js 

### state.json
See LP for `Primero Thailand Demo API User (Open Function)`

## Expected behavior
I'm worried this data `13.4 % (11 - 16 %)` isn't making it to Primero... but not quite sure what it should map to.

**Comment by lakhassane** [comment]
@aleksa-krolls the `undefined` we are seeing on `physical_form` are there because in the sample data there are `provis_labcode` values that we did not mapped in the job (probably because their mapping was not available).
I made a change to skipped those. Feel free to re-run
