### ISSUE TITLE
Verify `outpatient_number` mapping & re-format

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#8]
## Describe the bug
Search for `outpatient_number` in this run here: https://www.openfn.org/projects/p5kaap/runs/rd788jee
`"outpatient_number": "640421092321"`

Two issues...
1. If `vn` source value is defined, please format the number so it has 2 digits + '-' + remaining string (e.g., `64-0421092321`)

2. Also I cannot find this specific value `640421092321` in the first run sync with HIS. Search here: https://www.openfn.org/projects/p5kaap/runs/rk5ggneg
There is no `vn: 640421092321` in this run log, so I want to make sure we're mapping `outpatient_number` correctly in job 2 run. 

### expression.js
1b-upsertCases.js

### state.json
See LP for `Primero Thailand Demo API User (Open Function)`

## To test/resolve
Feel free to re-run this HIS sync: https://www.openfn.org/projects/p5kaap/runs/rk5ggneg

**Comment by lakhassane** [comment]
@aleksa-krolls I made the change for 1.

For 2. actually the run is truncated (check picture), reason why you can't see it. However that `vn` value is there (and was in the last 3 items).

<img width="346" alt="Screen Shot 2021-04-30 at 12 59 28" src="https://user-images.githubusercontent.com/8411231/116698439-e7e95200-a9b3-11eb-8265-eae9ddaf89ed.png">
