### ISSUE TITLE
Return empty string ' ' to overwrite all blank form values

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-thailand#9]
## Background, context, and business value
See issue #1 . Currently we sync form data from the HIS to Primero (e.g., `unexpected_pregnancy`). 
However, if a Primero user edits one of these form values... the integration will not overwrite this manually added value because `undefined` values do not create blank values. We must return an empty string `''` to overwrite values.

Therefore you'll see I made a change across many mappings to return `''` if no value defined: https://github.com/OpenFn/primero-thailand/commit/478a5015b9c247d0413a1bd2784a37757026ffa6#diff-d88739bbe882782655ef83d61013cd81ec74627470c75f6277d80928930bc49b

However, I'm not sure how to replicate the same logic for the mappings for `physical_check_2`, `new_pregnancy`, and 
`labOrderType` forms. 

## Request
Please add logic for the mappings for `physical_check_2`, `new_pregnancy`, and `labOrderType` forms to return default value of empty string `''` if no data value is defined in the HIS. 

## To test
1. User creates case in Primero: https://demo-care-thai-kids.primero.org/v2/cases/abd9f0f5-6556-40c1-925d-a10bac967c7d 
2. User syncs case with HIS --> 'Unexpected Pregnancy' form created where OpenFn uploads `pregnancy_test_21c37e2: undefined` because no data has been provided by HIS for this field. 
3. Let's say the user now manually edits this field to add a value `pregnancy_test_21c37e2: 'Test yes'`
4. The next time we sync the case, `pregnancy_test_21c37e2` should be reset to `pregnancy_test_21c37e2: ''` so that a blank value will appear to the user on the front end, overwriting the manually added value (`'Test yes'`) for this field. 

## expression
https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L377-L481

## adaptor
primero

**Comment by aleksa-krolls** [comment]
@lakhassane This is the priority new task today pls

**Comment by lakhassane** [comment]
@aleksa-krolls I implemented what we just talk about. Feel free to test and let me know.

**Comment by aleksa-krolls** [comment]
looking great !! @lakhassane :)
